[workspace]
authors = ["Aleks Rutins <keeper@farthergate.com>"]
channels = ["conda-forge", "https://prefix.dev/cheetah", "https://prefix.dev/brads-forge"]
name = "railpacked"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cheetah"
dev = "cheetah dev"

[dependencies]
cheetah = ">=0.4.1,<0.5"
bun = ">=1.3.1,<2"
